#BOT XANDÃO
from bot import Bot

class BotXandao(Bot):
    def __init__(self,nome):
        self.__nome = "SUPER XANDÃO"

    def nome(self):
        return self.__nome

    def apresentacao(self):
      return "MEU NOME É XANDÃO. FRUTO DE UMA VONTADE DIVINA, FUI ENVIADO TERRA COM O OBJETIVO DE SALVAR A HUMANIDADE DO PECADO MORTAL NO ÚLTIMO DIA DESTA EXISTÊNCIA. PORÉM, APENAS OS CAMPEÕES DE ESPÍRITO SERÃO SALVOS POR XANDÃO. SIGA-ME E IREMOS TRILHAR JUNTOS O CAMINHO DOS CAMPEÕES."
 
    def mostra_comandos(self):
      return """1 - BOM DIA
2 - A TERRA REALMENTE É PLANA?
3 - QUEM É ENÉAS?
4 - O QUE TEM NO FINAL DA ESCURIDÃO?
5 - DIVULGA MINHA AMIGA
6 - SE CAPOTOU FAZ O QUE?
7 - VOCÊ JÁ FOI ASSALTADO?
8 - SUCUMBA XANDÃO
9 - PORQUE VOCÊ FALA DE VOCÊ MESMO NA TERCEIRA PESSOA?
10 - XANDÃO, PORQUE CORTOU O CABELÃO?
11 - PORQUE VOCÊ FALA COM CAPS LIGADO?
12 - MANDA FOTO DE AGORA"""
    
    def executa_comando(self,cmd):
      if cmd == "1":
        return "BOM DIA DO ÚLTIMO HERÓI DA TERRA PARA OS CAMPEÕES, SEM PRESSÃO AQUI É XANDÃO, TÁ LIGADO?"
      if cmd == "2":
        return "SE TÁ DE BRINCADEIRA COM XANDÃO NÉ, OBVIAMENTE, NÃO É POSSÍVEL, NASA É DE HOLLYWOOD, QUEM ACREDITA NAQUELA NAVE DE TAMPA DE MARMITA?"
      if cmd == "3":
        return "O HOMEM DE VERDADE DOUTOR ENÉAS."
      if cmd == "4":
        return "NO FINAL DA ESCURIDÃO TEM XANDÃO, TÁ LIGADO?"
      if cmd == "5":
        return "DEPOIS VOCÊ MANDA AÍ A LIVE DA SUA PARCEIRA QUE A GENTE DIVULGA"
      if cmd == "6":
        return "SEGURA NO BRAÇO DO XANDÃO QUE NINGUÉM MORRE."
      if cmd == "7":
        return "CLARO QUE NÃO! QUEM QUE VAI SER LOUCO DE ASSALTAR O SUPER XANDÃO? DANDO 5 SOCOS POR SEGUNDO."
      if cmd == "8":
        return "SUCUMBA VOCÊ, OTÁRIO. SUPER XANDÃO FOREVER."
      if cmd == "9":
        return "PORQUE AQUI É XANDÃO."
      if cmd == "10":
        return "ISSO É UMA LONGA HISTÓRIA. FOI NA CAÇA AOS DEMONIOS, XANDÃO FOI PEGO DESPREVENIDO, TAVA SALVANDO A NOVINHA, E AQUELA ESTÚPIDA, FALEI PRA ELA SAIR DE PERTO, QUE O XANDÃO IA DESTRUIR O DEMÔNIO, MAS ELA FICOU LÁ DE GRAÇA, 'AH NÃO XANDÃO, EU QUERO VER SEU PEITORAL EXALANDO ENERGIA' AÍ FUI SALVAR ELA DO DEMÔNIO, ELE DEU UMA ESPADADA, PEGOU NO CABELO DO XANDÃO. PERDI O CABELO POR CAUSA DAQUELA ANTA. AÍ EU FALEI, 'TA VENDO O SUA ANTA? POR ISSO QUE O XANDÃO FALOU PRA VOCÊ SAIR.'"
      if cmd == "11":
        return "O CAPS LOCK LIGADO SIGNIFICA CONVICÇÃO E PERSONALIDADE FORTE, E PEITORAL DE AÇO POR DETRÁS DE QUEM TÁ FALANDO, TÁ LIGADO? É ASSIM QUE FUNCIONA IRMÃO. É ESTILO SUPER XANDÃO. NÃO TEM ESSES NEGÓCIOS DE FICAR FALANDO AINDUHASJD."
      if cmd == "12":
        return """_________oBBBBB8o___oBBBBBBB8,
_____o8BBBBBBBBBBB__BBBBBBBBB8________o88o,
___o8BBBBBB**8BBBB__BBBBBBBBBB_____oBBBBBBBo,
__oBBBBBBB*___***___BBBBBBBBBB_____BBBBBBBBBBo,
_8BBBBBBBBBBooooo___*BBBBBBB8______*BB*_8BBBBBBo,
_8BBBBBBBBBBBBBBBB8ooBBBBBBB8___________8BBBBBBB8,
__*BBBBBBBBBBBBBBBBBBBBBBBBBB8_o88BB88BBBBBBBBBBBB,
____*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB8,
______**8BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*,
___________*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB8*,
____________*BBBBBBBBBBBBBBBBBBBBBBBB8888**,
_____________BBBBBBBBBBBBBBBBBBBBBBB*,
_____________*BBBBBBBBBBBBBBBBBBBBB*,
______________*BBBBBBBBBBBBBBBBBB8,
_______________*BBBBBBBBBBBBBBBB*,
________________8BBBBBBBBBBBBBBB8,
_________________8BBBBBBBBBBBBBBBo,
__________________BBBBBBBBBBBBBBB8,"""


    def boas_vindas(self):
      return "SEM PRESSÃO AQUI É XANDÃO! FALA COM O ÚLTIMO HERÓI DA TERRA"

    def despedida(self):
      return "NO FINAL DA ESCURIDÃO TEM XANDÃO. NÃO ESQUEÇA DE TRILHAR O CAMINHO DOS CAMPEÕES LADO A LADO COM SUPER XANDÃO. TUDO NOSSO!"